version: '3'
services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@11
      MYSQL_DATABASE: test
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root@11
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
